name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - uses: ./
        with:
          base-url: ${{ secrets.KINTONE_BASE_URL }}
          app-id: ${{ vars.KINTONE_APP_ID }}
          username: ${{ secrets.KINTONE_USERNAME }}
          password: ${{ secrets.KINTONE_PASSWORD }}
          name: "Test App"
          description: "This is a test app"
      - run: test -f ./template.zip && echo "Template file exists"
        if: runner.os != 'Windows'
      - run: unzip ./template.zip -d ./template
        if: runner.os != 'Windows'
      - run: grep -q "Test App" ./template/01/manifest.json
        if: runner.os != 'Windows'
      - run: grep -q "This is a test app" ./template/01/manifest.json
        if: runner.os != 'Windows'
