name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          base-url: ${{ secrets.KINTONE_BASE_URL }}
          app-id: ${{ vars.KINTONE_APP_ID }}
          username: ${{ secrets.KINTONE_USERNAME }}
          password: ${{ secrets.KINTONE_PASSWORD }}
          name: "Test App"
          description: "This is a test app"
      - run: test -f ./template.zip && echo "Template file exists"
      - run: unzip ./template.zip -d ./template
      - run: grep -q "Test App" ./template/01/template.json
      - run: grep -q "This is a test app" ./template/01/template.json
